### ISSUE TITLE
Update `eks-hosted/README.md`

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-self-hosted-installers#58]
### What happened?

`eks-hosted/README.md` needs a few updates

1. The top `stackName` element isn't used anymore and should be remove
2. To be confirmed, but the `stackName` (see below) when connected to the Pulumi backend should include the `<orgName>` as shown below
3. The following elements are probably not optional anymore

```yaml
clusterConfig:
  stackName: aureq/aureq-selfhosted-01-cluster

clusterServicesConfig:
  stackName: aureq/aureq-selfhosted-02-cluster-services

appsConfig:
  stackName: aureq/aureq-selfhosted-03-apps
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
